version: "3.5"
services:

    neth_1:
        image: nethermindeth/nethermind:snap
        command: --config xdai --Pruning.Mode None
        expose:
            - 30303
        volumes:
            - ./neth_1/db:/nethermind/nethermind_db
            - ./neth_1/keystore:/nethermind/keystore
            - ./neth_1/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
            vpcin:
                ipv4_address: 10.4.0.2

    neth_2:
        image: nethermindeth/nethermind:snap
        command: --config xdai --Pruning.Mode None
        expose:
            -   30303
        volumes:
            - ./neth_2/db:/nethermind/nethermind_db
            - ./neth_2/keystore:/nethermind/keystore
            - ./neth_2/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4
            vpcin:
                ipv4_address: 10.4.0.4

    neth_3:
        image: nethermindeth/nethermind:snap
        command: --config xdai --Pruning.Mode None
        expose:
            - 30303
        volumes:
            - ./neth_3/db:/nethermind/nethermind_db
            - ./neth_3/keystore:/nethermind/keystore
            - ./neth_3/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6
            vpcin:
                ipv4_address: 10.4.0.6

    neth_4:
        image: nethermindeth/nethermind:snap
        command: --config xdai --Pruning.Mode None
        expose:
            - 30303
        volumes:
            - ./neth_4/db:/nethermind/nethermind_db
            - ./neth_4/keystore:/nethermind/keystore
            - ./neth_4/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.8
            vpcin:
                ipv4_address: 10.4.0.8

    neth_5:
        image: nethermindeth/nethermind:snap
        command: --config xdai --Pruning.Mode None
        expose:
            - 30303
        volumes:
            - ./neth_5/db:/nethermind/nethermind_db
            - ./neth_5/keystore:/nethermind/keystore
            - ./neth_5/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.10
            vpcin:
                ipv4_address: 10.4.0.10

    neth_6:
        image: nethermindeth/nethermind:snap
        command: --config xdai --Pruning.Mode None
        expose:
            - 30303
        volumes:
            - ./neth_6/db:/nethermind/nethermind_db
            - ./neth_6/keystore:/nethermind/keystore
            - ./neth_6/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcin:
                ipv4_address: 10.4.0.12

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
    vpcin:
        driver: bridge
        internal: true
        ipam:
            config:
                - subnet: 10.4.0.0/16

