version: "3.5"
services:

    neth_1:
        image: nethermindeth/nethermind:snap
        command: --config goerli --JsonRpc.Enabled true --JsonRpc.EngineHost=10.5.0.2 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Pruning.Mode None --Sync.SnapServe true
        volumes:
            - ./neth_1/db:/nethermind/nethermind_db
            - ./neth_1/keystore:/nethermind/keystore
            - ./neth_1/secret/jwt.hex:/nethermind/secret/jwt.hex
        ports:
            - 0.0.0.0:8547:8545
            - 0.0.0.0:3001:3000
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
            vpcin:
                ipv4_address: 10.4.0.2

    prysm_1:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.5.0.2:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_1/.eth2:/data
            - ./prysm_1/secret:/secret
        ports:
            - 0.0.0.0:4001:4000
            - 0.0.0.0:13001:13000
            - 0.0.0.0:12001:12000
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3
            vpcin:
                ipv4_address: 10.4.0.3
    neth_2:
        image: nethermindeth/nethermind:snap
        command: --config goerli --JsonRpc.Enabled true --JsonRpc.EngineHost=10.5.0.4 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Pruning.Mode None
        volumes:
            - ./neth_2/db:/nethermind/nethermind_db
            - ./neth_2/keystore:/nethermind/keystore
            - ./neth_2/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcin:
                ipv4_address: 10.4.0.4

    prysm_2:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.5.0.4:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_2/.eth2:/data
            - ./prysm_2/secret:/secret
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5
            vpcin:
                ipv4_address: 10.4.0.5

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
    vpcin:
        driver: bridge
        internal: true
        ipam:
            config:
                - subnet: 10.4.0.0/16

