version: "3.5"
services:

    neth_1:
        image: nethermindeth/nethermind:snap
        command: --config goerli --Pruning.Mode None --Sync.SnapServe true --JsonRpc.Enabled true --JsonRpc.EngineHost=10.4.0.2 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Network.StaticPeers="enode://f050a4c1a946a5677b0b3bfcc969c74cd341b05e70614548948e54da820eb7e52b05a5a4bf99dab399e816e665ab90ecd54ea896b065494bb5642050774c4b72@10.4.0.12:30303"
        expose:
            - 30303
        volumes:
            - ./neth_1/db:/nethermind/nethermind_db
            - ./neth_1/keystore:/nethermind/keystore
            - ./neth_1/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
            vpcin:
                ipv4_address: 10.4.0.2

    prysm_1:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.4.0.2:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_1/.eth2:/data
            - ./prysm_1/secret:/secret
        ports:
            - 0.0.0.0:4001:4000
            - 0.0.0.0:13001:13000
            - 0.0.0.0:12001:12000
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3
            vpcin:
                ipv4_address: 10.4.0.3
    neth_2:
        image: nethermindeth/nethermind:snap
        command: --config goerli --Pruning.Mode None --Sync.SnapServe true --JsonRpc.Enabled true --JsonRpc.EngineHost=10.4.0.4 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Network.StaticPeers="enode://f050a4c1a946a5677b0b3bfcc969c74cd341b05e70614548948e54da820eb7e52b05a5a4bf99dab399e816e665ab90ecd54ea896b065494bb5642050774c4b72@10.4.0.12:30303"
        expose:
            -   30303
        volumes:
            - ./neth_2/db:/nethermind/nethermind_db
            - ./neth_2/keystore:/nethermind/keystore
            - ./neth_2/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4
            vpcin:
                ipv4_address: 10.4.0.4

    prysm_2:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.4.0.4:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_2/.eth2:/data
            - ./prysm_2/secret:/secret
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5
            vpcin:
                ipv4_address: 10.4.0.5

    neth_3:
        image: nethermindeth/nethermind:snap
        command: --config goerli --Pruning.Mode None --Sync.SnapServe true --JsonRpc.Enabled true --JsonRpc.EngineHost=10.4.0.6 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Network.StaticPeers="enode://f050a4c1a946a5677b0b3bfcc969c74cd341b05e70614548948e54da820eb7e52b05a5a4bf99dab399e816e665ab90ecd54ea896b065494bb5642050774c4b72@10.4.0.12:30303"
        expose:
            - 30303
        volumes:
            - ./neth_3/db:/nethermind/nethermind_db
            - ./neth_3/keystore:/nethermind/keystore
            - ./neth_3/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6
            vpcin:
                ipv4_address: 10.4.0.6

    prysm_3:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.4.0.6:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_3/.eth2:/data
            - ./prysm_3/secret:/secret
        networks:
            vpcbr:
                ipv4_address: 10.5.0.7
            vpcin:
                ipv4_address: 10.4.0.7

    neth_4:
        image: nethermindeth/nethermind:snap
        command: --config goerli --Pruning.Mode None --Sync.SnapServe true --JsonRpc.Enabled true --JsonRpc.EngineHost=10.4.0.8 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Network.StaticPeers="enode://f050a4c1a946a5677b0b3bfcc969c74cd341b05e70614548948e54da820eb7e52b05a5a4bf99dab399e816e665ab90ecd54ea896b065494bb5642050774c4b72@10.4.0.12:30303"
        expose:
            - 30303
        volumes:
            - ./neth_4/db:/nethermind/nethermind_db
            - ./neth_4/keystore:/nethermind/keystore
            - ./neth_4/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.8
            vpcin:
                ipv4_address: 10.4.0.8

    prysm_4:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.4.0.8:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_4/.eth2:/data
            - ./prysm_4/secret:/secret
        networks:
            vpcbr:
                ipv4_address: 10.5.0.9
            vpcin:
                ipv4_address: 10.4.0.9

    neth_5:
        image: nethermindeth/nethermind:snap
        command: --config goerli --Pruning.Mode None --Sync.SnapServe true --JsonRpc.Enabled true --JsonRpc.EngineHost=10.4.0.10 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Network.StaticPeers="enode://f050a4c1a946a5677b0b3bfcc969c74cd341b05e70614548948e54da820eb7e52b05a5a4bf99dab399e816e665ab90ecd54ea896b065494bb5642050774c4b72@10.4.0.12:30303"
        expose:
            - 30303
        volumes:
            - ./neth_5/db:/nethermind/nethermind_db
            - ./neth_5/keystore:/nethermind/keystore
            - ./neth_5/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.10
            vpcin:
                ipv4_address: 10.4.0.10

    prysm_5:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.4.0.10:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_5/.eth2:/data
            - ./prysm_5/secret:/secret
        networks:
            vpcbr:
                ipv4_address: 10.5.0.11
            vpcin:
                ipv4_address: 10.4.0.11

    neth_6:
        image: nethermindeth/nethermind:snap
        command: --config goerli --Pruning.Mode None --Sync.SnapServe true --JsonRpc.Enabled true --JsonRpc.EngineHost=10.4.0.12 --JsonRpc.EnginePort 8546 --JsonRpc.JwtSecretFile=secret/jwt.hex --Network.StaticPeers=""enode://5b05d919ab67448a42d2e12fa690f2a4cb4269ed210b5142fff0ce3b09021d97036f4f94581b20cc3cf4802be3f9ae2ba4b0c5201b7c1b3f37007c74feb99064@10.4.0.2:30303,enode://d811bb5b62c3ad907f5887971ed90cb329419e3901e959aa988bdc5a8daf5a1e5a8683f5504c7526ec0c0ed442a2af2e5edd1212e07ad4bdb851c0df15b7391b@10.4.0.4:30303,enode://b20c31405b66c9646e52728ab9367e0bb01997d0865d55c128878069ac09afea0031ca02ae714d8d8f6a3929e02369b40bc483234201d389310a33dbd4242ed8@10.4.0.6:30303,enode://5d5f11ed48a89a62c169c80c5532da99da5b4bc237c5b297cae1e8dd8aeb672c34d478f5279ce96174bb9f17525ecec8dfa345afb9b24b5fb299bdabf1893fc4@10.4.0.8:30303,enode://927486899751433d417ccf54d34195d8b78317b68b9d278ab77ac886e484329a312967987dbb2efdfcb1ade3ca5993ec380b6d04dbecd9df1eda33c65820b6a6@10.4.0.10:30303"
        expose:
            - 30303
        volumes:
            - ./neth_6/db:/nethermind/nethermind_db
            - ./neth_6/keystore:/nethermind/keystore
            - ./neth_6/secret/jwt.hex:/nethermind/secret/jwt.hex
        networks:
            vpcbr:
                ipv4_address: 10.5.0.12
            vpcin:
                ipv4_address: 10.4.0.12

    prysm_6:
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        command: --accept-terms-of-use --prater --datadir=/data --jwt-secret=/secret/jwt.hex --execution-endpoint=http://10.4.0.12:8546 --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethdevops.io
        volumes:
            - ./prysm_6/.eth2:/data
            - ./prysm_6/secret:/secret
        networks:
            vpcin:
                ipv4_address: 10.4.0.13

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
    vpcin:
        driver: bridge
        internal: true
        ipam:
            config:
                - subnet: 10.4.0.0/16

